import type { Metadata } from "next";

import "./globals.css";
import { AppContextProvider } from "@/hooks/AppContext";
import React from "react";







export const metadata: Metadata = {
  title: "Create Next App", description"Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${raleway.variable} ${dancingScript.variable} ${poppins.variable} antialiased`}
      >
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
