export const images = {
  Logo: "/logo.png",
  LogoBlue: "/logoBlue.png",
  LogoBrown: "/logoBrown.png",
  LogoLight: "/logoLight.png",
  Hero: "/main2.jpg",
  Hero2: "/main1.jpg",
  Hero3: "/main3.jpg",
  Hero4: "/main4.jpg",
  card1: "/HarmonyS.jpg",
  card2: "/HomelandE.jpg",
  card3: "/HarmonyS.jpg",
  Person1: "/me.jpeg",
  Room1: "/room1.webp",
  Room2: "/room2.webp",
  Room3: "/room3.webp",
  Gym: "/explore_gym.png",
  Restaurant: "/explore_restaurant.png",
  Avatar1: "/guest_avatar1.png",
  Avatar2: "/guest_avatar2.png",
  Avatar3: "/guest_avatar3.png",
};
